name: "😀test_workflow"
on: 
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 5'
jobs:
  buid-job:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - run: ./build_cnt.sh